#ifndef _AVR_HELPER_H_
#define _AVR_HELPER_H_

#define SETBIT(ADDRESS,BIT) (ADDRESS |= (1 <<BIT))
#define CLEARBIT(ADDRESS,BIT) (ADDRESS &= ~(1<<BIT))
#define FLIPBIT(ADDRESS,BIT) (ADDRESS ^= (1<<BIT))
#define CHECKBIT(ADDRESS,BIT) (ADDRESS & (1<<BIT))
#define WRITEBIT(RADDRESS,RBIT,WADDRESS,WBIT) (CHECKBIT(RADDRESS,RBIT) ? SETBIT(WADDRESS,WBIT) : CLEARBIT(WADDRESS,WBIT))

#define LOW 0
#define HIGH 1
#define OUTPUT 1
#define INPUT 0

#endif